Catstagram/config/routes.rb
Rails.application.routes.draw do
  resources :roles

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :hashtags do
    collection do
      get :index_admin
    end
  end
  resources :photos do
    collection do
      get :reported
    end 
    member do
      get :like
      get :report
      get :reset
    end
  end
  resources :cats
  resources :users do
    collection do
      get :banned
    end 
    member do
      get :ban
      put :ban_update
      put :save_roles
      get :edit_roles
    end
  end

  get 'users/:id#:sect', to: 'users#show', as: 'user_show_section'

  get '403.html', to: 'users#access_denied', as: 'access_denied'

  root to: 'photos#index_main', as: 'index'
  get '/search/', to: 'photos#search', as: 'search_query'
  get '/search/:criteria', to: 'photos#search', as: 'search_url'

end

Catstagram/app/models/photo.rb
class Photo < ActiveRecord::Base
  has_and_belongs_to_many :hashtags
  has_and_belongs_to_many :cats
  belongs_to :user
  
  mount_uploader :image_url, ImageUploader
  
  validates_processing_of :image_url
  validate :image_size_validation

  # returns true if a picture is reported.
  def is_reported?
    (report_count > 0)
  end

  # returns true if a picture is newer than 5 min (for the purpose of the presentation)
  def is_new?
    (created_at > Time.now - 5.minutes)
  end
  
  private
    def image_size_validation
      errors[:image_url] << " should be less than 5MB" if image_url.size > 5.megabytes
    end
end

Catstagram/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy, :like_update, :report_update]

  # Load authorization ressources for everything.
  load_and_authorize_resource :except => [:index_main, :search]

  # Like & report authorization are manually handled! BE CARFEFUL!
  skip_authorize_resource :only => [:like, :report, :reset]

  #======================================================================
  ## WARNING - LIKE & REPORT & RESET ARE OPEN TO ALL USER WITH THESE RIGHTS!
  ## DO NOT TRUST USER INPUT / DO NOT MODIFY OTHER THINGS IN THE PHOTO.
  # Moreover, its impossible to restrict a user to like/report/reser it own photo with cancancan
  # (as the owner has full rights over the photo...) but we do it programmatically in the reply!
  def like
    authorize! :like_photo, @photo

    if current_user != @photo.user
      @photo.increment!(:like_count, 1)
      render 'update_likes.js'
    else
      respond_to do |format|
        format.html {redirect_to @photo, alert: "You can't like your own photo, you narcissistic self-obsessed user!"}
      end
    end

    # respond_to do |format|
    #   if current_user == @photo.user
    #     format.html {redirect_to @photo, notice: "You can't like your own photo, you narcissistic self-obsessed user!"}
    #   else
    #     @photo.increment!(:like_count, 1)
    #     format.html {redirect_to @photo, notice: "Thank you for the like <3"}
    #   end
    # end
  end

  def report
    authorize! :report_photo, @photo
    respond_to do |format|
      if current_user == @photo.user
        format.html {redirect_to @photo, alert: "Cannot report your own photo, unfortunately."}
      else
        @photo.increment!(:report_count, 1)
        format.html {redirect_to @photo, notice: "Report sent"}
      end
    end
  end

  def reset
    authorize! :reset_report_photo, @photo
    respond_to do |format|
      if current_user == @photo.user
        format.html {redirect_to @photo, alert: "Cannot reset report on your own picture..."}
      else
        @photo.update_attribute(:report_count, 0)
        format.html {redirect_to @photo, notice: "Report value reset"}
      end
    end
  end

  # same as index, but only for the admin, and only reported photos.
  def reported
    #ordered by report count, then by most recent
    @photos = Photo.where("report_count > 0").order(report_count: :desc, created_at: :desc)
    if (@photos.size > 0)
      @title = "Reported photos"
    else
      @title = "No reported photos"
    end
    render 'index'
  end

  #======================================================================
  # DEFAULT REST METHODS

  # GET /photos
  # GET /photos.json
  def index
    # most recent picture first!
    @title = "Latest photos"
    @photos = Photo.all.order(created_at: :desc)
  end

  def index_main
    # most recent picture first!
    @title_main = "Welcome on Catstagram !"
    @title = "Latest Photos"
    @photos = Photo.all.order(created_at: :desc).limit(8)
    @hashtags = Hashtag.all.order(created_at: :desc).limit(4)
    @users = User.all.order(created_at: :desc).limit(4)
    @cats = Cat.all.order(created_at: :desc).limit(4)
    @title_user = "Latest Users"
    @title_tag = "Latest Hashtags"
    @title_cat = "Latest Cats"
    render 'layouts/index'
  end

  def search
    # extract param & check its not nul or empty.
    tk = params[:criteria]
    if (tk == nil or tk == '')
      redirect_to photos_path
    else
      token_like = "%" + tk + "%"
      @title_main = "Search result for '" + tk + "'"

      @title = "Latest Photos"
      # most recent first!
      @photos = Photo.where("caption LIKE :token" , {token: token_like }).order(created_at: :desc)
      @hashtags = Hashtag.where("tag LIKE :token" , {token: token_like }).order(created_at: :desc)
      @users = User.where("username LIKE :token OR biography LIKE :token" , {token: token_like }).order(created_at: :desc)
      @cats = Cat.where("catname LIKE :token OR description LIKE :token OR city LIKE :token" , {token: token_like}).order(created_at: :desc)
      @title_user = "Latest Users"
      @title_tag = "Latest Hashtags"
      @title_cat = "Latest Cats"
      render 'layouts/index'
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo.increment!(:view_count, 1)
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user

    set_tags

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    set_tags

    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_tags
      tags_param = params[:hashtags]

      @hashtags = []
      if tags_param
        tags_param.each do |t|
          unless t.blank?
            tag = t.downcase
            current = Hashtag.find_by(tag: tag)
            if current
              p "loading existing: " + tag
              @hashtags.push(current)
            else
              p "creating new: " + tag
              tag = Hashtag.create(:tag => tag)
              @hashtags.push(tag)
            end
          end
        end
      end

      @photo.hashtags = @hashtags.uniq
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image_url, :caption,
                                    :cat_ids => [],
                                    :hashtags => [])
    end
end

Catstagram/app/helpers/photos_helper.rb
module PhotosHelper
end

Catstagram/app/views/photos/_form.html.erb
<%= form_for @photo, :html => {:class => "form-horizontal"} do |f| %>
  <% if @photo.errors.any? %>
    <div class="alert alert-dismissible alert-danger" id="error_explanation">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="well bs-component">
    <fieldset>
      <div class="form-group">
        <% if f.object.image_url? %>
          <div class="col-lg-2" control-label>
            <center>
              <%= image_tag f.object.image_url.thumb.url %>
            </center>
          </div>
        <% else %>
          <%= f.label :image, :class => "col-lg-2 control-label" %>
        <% end %>
        <div class="col-lg-10">
          <%= f.file_field :image_url %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Cats on photo (use cmd or ctrl to select multiple cats)", :class => "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.collection_select :cat_ids, Cat.all, :id, :catname, {}, {:multiple => true, :class => "form-control"} %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :caption, :class => "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :caption, :class => "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label "Tags", :class => "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <div id="tags">
            <% if @photo.new_record? %>
              <%= render 'tag_input', tag_name: "" %>
            <% else %>
              <% @photo.hashtags.each do |tag| %>
                <%= render "tag_input", tag_name: tag.tag %>
              <% end %>
            <% end %>
          </div>
          <a href="javascript:;", id="addTag">Add Tag</a>
        </div>
      </div>

      <div class="form-group actions">
        <div class="col-lg-10 col-lg-offset-2">
          <%= f.submit @photo.new_record? ? "Publish Photo" : "Edit Photo", :class => "btn btn-primary" %>
        </div>
      </div>
    </fieldset>
  </div>
<% end %>

<div style="display: none;" id="new_tag_form">
  <%= render "tag_input", tag_name: "" %>
</div>

Catstagram/app/views/photos/_grid.html.erb
<!-- DEFINE FIRST @photo the collection to show and @title -->

<p>
  <h3 id="photos"><%= @title + " (" + @photos.count.to_s + ")" %>:</h3>
  <% unless @photos.any? %>
    No photos yet!
  <% end %>
  <% @photos.each_slice(4) do |photos| %>
    <div class="row">
      <% photos.each do |photo| %>
        <%= link_to photo do %>
          <div class="col-lg-3">
            <div class="panel panel-default">
              <div class="panel-heading">
                <!-- Show number of views, like, cats, and reports (if any) -->
                <%= photo.view_count %> &#8635; <!-- CLOCKWISE OPEN CIRCLE ARROW -->
                <%= photo.like_count %> &hearts;
                <%= photo.cats.size %> &#128049; <!-- cats -->
                
                </br> 
                <% if photo.is_reported? %>
                  <% if can? :report_photo, photo or can? :test, photo %>
                    <%= photo.report_count %> &#9888; <!-- WARNING SIGN -->
                  <% end %>
                  <% if can? :manage, photo or can? :test, photo %>
                    <span class="label label-warning"> REPORTED </span>
                  <% end %>
                <%end%>
                <% if current_user != nil and current_user == photo.user %>
                    <span class="label label-info"> Yours! </span>
                <% end %>
                <% if photo.is_new? %>
                    <span class="label label-success"> new </span>
                <% end %>
                  .
              </div>
              <div class="panel-body">
                <center>
                  <%= image_tag photo.image_url.thumb.url %><br>  
                </center>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</p>

Catstagram/app/views/photos/_tag_input.html.erb
<div class="tagForm">
  <%= text_field_tag"hashtags[]", tag_name %>
  <a href="#" onclick="removeTag($(this))" class="remove-tag"> x </a>
</div>

Catstagram/app/views/photos/edit.html.erb
<div class="pull-right">
  <%= link_to "Return to photo", @photo, :class => "btn btn-info" %>
</div>

<h1>Editing Photo</h1>

<%= render 'form' %>

Catstagram/app/views/photos/index.html.erb
<% if user_signed_in? %>
  <div class="pull-right">
    <%= link_to 'Post new photo', new_photo_path, :class => "btn btn-success" %>
  </div>
<% end %>

<h1> Photos on Catstagram </h1>

<%= render 'photos/grid' %>

Catstagram/app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form' %>

Catstagram/app/views/photos/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <center>
      <%= image_tag @photo.image_url %><br><br>
    </center>
    <%= link_to "by " + @photo.user.username, @photo.user if @photo.user %>
    <br><br>
    <strong> Uploaded: <%= @photo.created_at %> </strong>
    <br><br>
    <% unless @photo.caption.blank? %>
      <blockquote>
        <p><%= @photo.caption %></p>
      </blockquote>
    <% end %>

    <% if @photo.cats.any? %>
      <h3>Cats featured in this photo:</h3>
      <% @photo.cats.each_slice(4) do |cats| %>
        <div class="row">
          <% cats.each do |cat| %>
            <%= link_to cat do %>
              <div class="col-lg-3">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <%= cat.catname %>
                  </div>
                  <div class="panel-body">
                    <center>
                      <%= image_tag cat.photos.last.image_url.thumb.url %>
                    </center>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end %>

    <div class="pull-right">
      <!-- Managing buttons (Edit, Delete) -->
      <% if can? :manage, @photo or can? :test, @photo %>
        <%= link_to "Edit", edit_photo_path(@photo), :class => "btn btn-warning" %>
        <%= link_to 'Delete', @photo, method: :delete, data: { confirm: 'Are you sure to delete this photo?' }, :class => "btn btn-danger" %>
      <% end %>
    </div>
  </div>

  <div class="panel-footer">
    <% @photo.hashtags.each do |tag| %>
      <%= link_to "#" + tag.tag, tag %>
    <% end %>
    &nbsp;
    <div class="pull-right">
      <!-- buttons to like, report and reset the reports (if any) -->
      <% if current_user != @photo.user %>
        <% if can? :like_photo, @photo or can? :test, @photo %>
          <%= link_to 'Like', like_photo_path(@photo), id: "like", class: "btn btn-xs btn-success", remote: true %> &nbsp;
        <% end %>
        <% if can? :report_photo, @photo or can? :test, @photo %>
          <%= link_to "Report", report_photo_path, data: { confirm: 'Are you sure to report this photo?' }, :class => "btn btn-xs btn-danger" %> &nbsp;
        <% end %>
        <% if @photo.is_reported? and (can? :reset_report_photo, @photo or can? :test, @photo) %>
          <%= link_to "Reset reports (" + @photo.report_count.to_s + ")", reset_photo_path(@photo), data: { confirm: 'Are you sure to reset the report count of this photo?' }, :class => "btn btn-xs btn-danger" %> &nbsp;
        <% end %>
      <% end %>

      <!-- Show number of views, like, and reports (if any) -->
      <%= @photo.view_count %> &#8635; <!-- CLOCKWISE OPEN CIRCLE ARROW -->
      <span id="like_count"><%= @photo.like_count %></span> &hearts;
      <%= @photo.cats.size %> &#128049;
      <% if @photo.is_reported? %>
        <% if can? :report_photo, @photo or can? :test, @photo %>
          <%= @photo.report_count %> &#9888; <!-- WARNING SIGN -->
        <% end %>
        <% if can? :manage, @photo or can? :test, @photo %>
          <span class="label label-warning"> REPORTED </span>
        <% end %>
      <%end%>
      <% if current_user != nil and current_user == @photo.user %>
        <span class="label label-info"> Yours! </span>
      <% end %>
      <% if @photo.is_new? %>
        <span class="label label-success"> new </span>
      <% end %>
    </div>
  </div>
</div>