Catstagram/config/routes.rb
Rails.application.routes.draw do
  resources :roles

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :hashtags do
    collection do
      get :index_admin
    end
  end
  resources :photos do
    collection do
      get :reported
    end 
    member do
      get :like
      get :report
      get :reset
    end
  end
  resources :cats
  resources :users do
    collection do
      get :banned
    end 
    member do
      get :ban
      put :ban_update
      put :save_roles
      get :edit_roles
    end
  end

  get 'users/:id#:sect', to: 'users#show', as: 'user_show_section'

  get '403.html', to: 'users#access_denied', as: 'access_denied'

  root to: 'photos#index_main', as: 'index'
  get '/search/', to: 'photos#search', as: 'search_query'
  get '/search/:criteria', to: 'photos#search', as: 'search_url'

end

Catstagram/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :photos, {:dependent => :destroy}
  has_many :cats

  has_and_belongs_to_many :roles

  mount_uploader :avatar_url, ImageUploader
  
  validates_processing_of :avatar_url
  validate :image_size_validation

  # check role
  def has_role?(role)
    return self.roles.find_by(:name => role.to_s.camelize)
  end

  # check admin role
  def is_admin? 
    return self.has_role?(:admin)
  end

  # check user role
  def is_user? 
    return self.has_role?(:user)
  end

  # check tester role
  def is_tester? 
    return self.has_role?(:tester)
  end

  #Returns if there are reported photos (it is the only model accessible everywhere!)
  def has_reported_photo?
    return (Photo.where("report_count > 0").size > 0)
  end

  #Returns the number of reported photos (it is the only model accessible everywhere!)
  def number_reported_photo?
    return Photo.where("report_count > 0").size
  end

  #Returns the number of banned users photos (it is the only model accessible everywhere!)
  def number_banned_users?
    User.all.select{ |u| u.is_banned }.size
  end

  def roles_as_text
    text = ''
    self.roles.each do |role|
      text += role.name + " "
    end
    return text
  end
  
  ## Checks if a user is banned given its banned_until value
  def is_banned
  	if (nil == banned_until) then
  	  false
    elsif (Time.now <= banned_until) then
      true
    else
      false
    end
  end

  def image_size_validation
    errors[:avatar_url] << " should be less than 5MB" if avatar_url.size > 5.megabytes
  end
end

Catstagram/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :ban, :ban_update, :edit_roles, :save_roles]

  #before_filter :authenticate_user!, only: [:edit, :update, :destroy, :ban, :ban_update, :edit_roles, :save_roles]
  load_and_authorize_resource :except => [:index]
  skip_authorize_resource :only => [:access_denied]


  # GET /users
  # GET /users.json
  def index
    # for partial generic views
    @title_user = "All Catstagram Users"
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @title = "Photos uploaded by " + @user.username
    @title_cat = "Cats belonging to " + @user.username
    # for partial generic views
    @photos = @user.photos
    @cats = @user.cats
  end

  # GET /users/1/edit
  def edit
  end

  # GET /users/banned
  # same as index but only banned users.
  def banned
    authorize! :change_banned, @current_user
    if !current_user.is_admin?
      format.html {redirect_to users_path, alert: "You can't see banned people."}
    else 
      @users = User.all.select{ |u| u.is_banned }
      @title_user = "Banned Users"
      render 'index'
    end
  end


  # GET /users/1/ban
  # Automatically renders ban.html.erb
  def ban
    authorize! :change_banned, @user
    if current_user == @user
      redirect_to @user, alert: "You can't ban yourself!"
    else 
      render 'ban'
    end
  end

  # PATCH/PUT /users/1/ban
  # PATCH/PUT /users/1.json/ban
  # Allows the update of banned_until field 
  def ban_update
    authorize! :change_banned, @user
    respond_to do |format|
      if current_user == @user
        format.html {redirect_to @user, alert: "You can't ban yourself!"}
      elsif @user.update(ban_params)
        format.json { render :ban, status: :ok, location: @user }
        if @user.is_banned
          format.html { redirect_to @user, notice: 'User was successfully banned.' }
        else 
          format.html { redirect_to @user, notice: 'User was successfully unbanned.' }
        end
      else
        format.html { render :ban }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit_roles
    authorize! :manage, Role
  end

  def save_roles
    authorize! :manage, Role
    @user.roles.each do |role|
      @user.roles.delete(role)
    end

    if params[:user]
      for id_role in params[:user][:role_ids]
        role = Role.find(id_role)
        @user.roles << role
      end
    end

    redirect_to users_path
  end

  def access_denied
    #304 rendering.
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      # automatically add user right when we see the user
      # /!\ it add to every and single user visited!
      if !@user.is_user?
        @user.roles << Role.where(name: 'user').first_or_create
      end
    end

    # Ban may only edit banned_until param
    def ban_params
      params.require(:user).permit(:banned_until)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # Does not allow :banned_until parameter
    def user_params
      params.require(:user).permit(:username, :avatar_url, :biography)
    end
end

Catstagram/app/helpers/users_helper.rb
module UsersHelper
end

Catstagram/app/views/users/_form.html.erb
<%= form_for @user, :html => {:class => "form-horizontal"} do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-dismissible alert-danger" id="error_explanation">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="well bs-component">
    <fieldset>
      <div class="form-group">
        <% if f.object.avatar_url? %>
          <div class="col-lg-2" control-label>
            <center>
              <%= image_tag f.object.avatar_url.thumb.url %>
            </center>
          </div>
        <% else %>
          <%= f.label :avatar, :class => "col-lg-2 control-label" %>
        <% end %>
        <div class="col-lg-10">
          <%= f.file_field :avatar_url %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :username, :class => "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_field :username, :class => "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :biography, :class => "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= f.text_area :biography, :class => "form-control" %>
        </div>
      </div>

      <div class="form-group actions">
        <div class="col-lg-10 col-lg-offset-2">
          <%= f.submit @user.new_record? ? "Create User" : "Edit User", :class => "btn btn-primary" %>
        </div>
      </div>
    </fieldset>
  </div>
<% end %>

Catstagram/app/views/users/_grid.html.erb
<p>
  <h3 id="users"><%= @title_user + " (" + @users.count.to_s + ")" %>:</h3>
  <% unless @users.any? %>
    No users yet!
  <% end %>

  <% @users.each_slice(4) do |users| %>
    <div class="row">
      <% users.each do |user| %>
        <%= link_to user do %>
          <div class="col-lg-3">
            <% if user_signed_in? and current_user == user %>
              <div class="panel panel-success">
            <% else %>
              <div class="panel panel-default">
            <% end %>
                <div class="panel-heading">
                  <%= user.username %>
                  <div class="pull-right">
                    <strong><%= user.cats.count %></strong> &#128049; <!-- cats -->
                    <strong><%= user.photos.count %></strong> &#128247; <!-- photos -->
                    <!-- only authorized users -->
                    <% if can? :see_banned, user and user.is_banned %>
                      <span class="label label-warning">Banned</span>
                    <% end %>
                    <% if user.is_admin? %>
                      <span class="label label-info">Admin</span>
                    <% end %>
                  </div>
                </div>
                <div class="panel-body">
                  <center>
                    <% unless user.avatar_url.blank? %>
                      <%= image_tag user.avatar_url.thumb %><br>
                    <% end %>
                  </center>
                </div>
              </div>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</p>

Catstagram/app/views/users/access_denied.erb
<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Error 403 : Forbidden/Unauthorized. ACCESS IS DENIED.</h3>
  </div>
  <div class="panel-body">
    You're not authorized to see or access this resource, and it caused
    an
    <%= link_to 'HTTP 403 FORBIDDEN' ,'https://en.wikipedia.org/wiki/HTTP_403' %>
    error.

    <p>
    <!-- display different message for logged user and guest. -->
    <% if user_signed_in? %>
      <strong>
        You're connected as 
        <%= current_user.username %>
        (<%= current_user.email %>). 
      </strong><br>

      You probably don't have sufficient access rights. Ask an admin for more information. <br>

      If you have another account with different rights, you might want to 
      <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
      and log in again with the other account.
    <% else %>
      Some features are reserved for registered users. <br>

      Try to connect with
      <%= link_to 'Log in', new_user_session_path %> 
      or to create an account with
      <%= link_to 'Sign up', new_user_registration_path %>.
    <% end %>
    </p>
  </div>
</div>

Catstagram/app/views/users/ban.html.erb
<div class="pull-right">
  <%= link_to "Return to " + @user.username + "'s profile", @user, :class => "btn btn-info" %>
</div>

<h1>Ban User <%= @user.username %></h1>

<%= form_for @user, url: {controller: "users", action: "ban_update"}, method: "put", class: "ban_form", :html => {:class => "form-horizontal"} do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-dismissible alert-danger" id="error_explanation">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="well bs-component">
    <fieldset>
      <div class="form-group">
        <div class="col-lg-12">
          <p>
            Enter the date until which the user must be banned (format: YYYY-MM-DD or DD/MM/YYYY). Dates before the current date or empty value will unban the user.
          </p>
        </br>
        </div>
      </div>
      <div class="form-group">
        <%= f.label "Ban until", :class=> "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <%= date_field(:user, :banned_until) %><br><br>
        </div>
      </div>

      <div class="form-group actions">
        <div class="col-lg-10 col-lg-offset-2">
          <%= f.submit "Ban User", :class => "btn btn-danger" %>
        </div>
      </div>
    </fieldset>
  </div>
<% end %>

Catstagram/app/views/users/edit.html.erb
<div class="pull-right">
  <%= link_to "Return to " + @user.username + "'s profile", @user, :class => "btn btn-info" %>
</div>

<h1>Editing User "<%= @user.username %>"</h1>

<%= render 'form' %>

Catstagram/app/views/users/edit_roles.erb
<div class="pull-right">
  <%= link_to "Return to " + @user.username + "'s profile", @user, :class => "btn btn-info" %>
</div>

<h1>Roles attributed to <%= @user.username %> </h1>

<%= form_for(@user, :url => save_roles_user_path(@user), method: :put, :html => {:class => "form-horizontal"}) do |f| %>

  <div class="well bs-component">
    <fieldset>
      <div class="form-group">
        <%= f.label "Roles", :class => "col-lg-2 control-label" %>
        <div class="col-lg-10">
          <% for role in Role.all %>
            <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>
            <%= role.name %><br>
          <% end %>
        </div>
      </div>

      <div class="form-group actions">
        <div class="col-lg-10 col-lg-offset-2">
          <%= f.submit "Sauvegarder", :class => "btn btn-info" %>
        </div>
      </div>
    </fieldset>
  </div>
<% end %>

Catstagram/app/views/users/index.html.erb
<h1> Users on Catstagram </h1>

<%= render 'grid' %>

Catstagram/app/views/users/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <div class="pull-right">
      <br>
      <% if user_signed_in? and current_user.is_admin? %>
        <% 
        text = "Ban"
        if @user.is_banned
          text = "Unban"
        end
        %>
        <%= link_to text, ban_user_path(@user), :class => "btn btn-danger" %>
        <%= link_to 'Edit Roles', edit_roles_user_path(@user), :class => "btn btn-info" %>
      <% end %>
      <% if user_signed_in? and (current_user == @user or current_user.is_admin?)%>
        <%= link_to "Edit", edit_user_path(@user), :class => "btn btn-warning" %>
        <%= link_to 'Delete', @user, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
      <% end %>
    </div>
    <h1>
      <%= @user.username %>
      <% if @user.roles_as_text.include? "admin" %>
        <span class="label label-info">Admin</span>
      <% end %>
    </h1>
  </div>
  <div class="panel-body">
    <% if (@user.is_banned) %>
      <div class="alert alert-dismissible alert-danger">
        User is <strong>banned</strong> until <%= @user.banned_until %>
      </div>
    <% end %>
    <% unless @user.avatar_url.blank? %>
      <%= image_tag @user.avatar_url, :style => "height:100px;" %>
    <% end %>
    <% unless @user.biography.blank? %>
      <blockquote>
        <%= @user.biography %>
      </blockquote>
    <% end %>
    <strong>Joined at:</strong> <%= @user.created_at %>

    <%= render 'cats/grid' %>

    <%= render 'photos/grid' %>
  </div>
</div>