Catstagram/config/routes.rb
Rails.application.routes.draw do
  resources :roles

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :hashtags do
    collection do
      get :index_admin
    end
  end
  resources :photos do
    collection do
      get :reported
    end 
    member do
      get :like
      get :report
      get :reset
    end
  end
  resources :cats
  resources :users do
    collection do
      get :banned
    end 
    member do
      get :ban
      put :ban_update
      put :save_roles
      get :edit_roles
    end
  end

  get 'users/:id#:sect', to: 'users#show', as: 'user_show_section'

  get '403.html', to: 'users#access_denied', as: 'access_denied'

  root to: 'photos#index_main', as: 'index'
  get '/search/', to: 'photos#search', as: 'search_query'
  get '/search/:criteria', to: 'photos#search', as: 'search_url'

end

Catstagram/app/views/layouts/_banned.erb
<!-- partial for banned users -->

<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title"> You're a banned user. ACCESS IS DENIED.</h3>
  </div>
  <div class="panel-body">
    You're not authorized to see or access this resource, because your account is banned.

    <p>
    <!-- display different message for logged user and guest. -->
    <% if user_signed_in? %>
      <strong>
        Banned until: <%= current_user.banned_until %>
        <br>
        You're connected as 
        <%= current_user.username %>
        (<%= current_user.email %>). 
      </strong><br>

      Ask an admin for more information if you believe this is an error. <br>

      If you have another account with different rights, you might want to 
      <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
      and log in again with the other account.
    <% else %>
      Some features are reserved for registered users. <br>

      Try to connect with
      <%= link_to 'Log in', new_user_session_path %> 
      or to create an account with
      <%= link_to 'Sign up', new_user_registration_path %>.
    <% end %>
    </p>
  </div>
</div>

Catstagram/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catstagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Navbar from https://bootswatch.com/sandstone/#navbar-->
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Catstagram', index_path, { :class=>"navbar-brand" } %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <!-- Indexes of 4 data models-->
        <li>
          <%= link_to 'Photos', photos_path %>
        </li>
        <li>
          <%= link_to 'Cats', cats_path %>
        </li>
        <li>
          <%= link_to 'Users', users_path %>
        </li>
        <li>
          <%= link_to 'Hashtags', hashtags_path %>
        </li>
      </ul>
      <%= form_tag ("/search"), method: "get", class: "navbar-form navbar-left" do  %> -->

          <div class="form-group">
            <input type="text" name="criteria" class="form-control" placeholder="Search everywhere...">
          </div>
          <div class="form-group actions">
              <%= submit_tag ("Search"), :class => "btn btn-default" %> 
          </div>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <!-- Admin NavBar -->
          <% if current_user.is_admin? %>
            <!-- show the warning only if there are reported users -->
            <% if current_user.has_reported_photo? %>
              <li>
                <a href="/photos/reported"> New Reports <span class="badge">
                  <%= current_user.number_reported_photo? %>
                </span></a>
              </li>
            <% end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin Actions<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to 'Show Hashtags for Admin', index_admin_hashtags_path %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to 'Show Roles', roles_path %>
                </li>
                <li>
                  <%= link_to 'New Role', new_role_path %>
                </li>
                <li>
                  <%= link_to 'Edit my roles', edit_roles_user_path(current_user) %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to 'View Reported Photos (' + current_user.number_reported_photo?.to_s + ')' , reported_photos_path %>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to 'View Banned Users (' + current_user.number_banned_users?.to_s + ')', banned_users_path %>
                </li>
              </ul>
            </li>
          <% end %>
          <!-- User NavBar -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to "My profile", current_user %>
              </li>
              <li>
                <a href=<%= user_path(current_user.id) %>#cats> My Cats (<%= current_user.cats.count %>) </a>
              </li>
              <li>
                <a href=<%= user_path(current_user.id) %>#photos> My Photos (<%= current_user.photos.count %>) </a>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to "Change password", edit_user_registration_path %>
              </li>
              <li>
                <%= link_to "Edit profile", edit_user_path(current_user) %>
              </li>
            </ul>
          </li>
        <% else %>
          <!-- Guest Buttons -->
          <li>
            <%= link_to 'Sign up', new_user_registration_path %>
          </li>
          <li>
            <%= link_to 'Log in', new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">

  <!-- for flash message, eg from devise -->
  <% if flash[:alert] %>
    <div class="alert alert-dismissible alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
  <% if flash[:notice] %>
    <div class="alert alert-dismissible alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% end %>

  <!-- change to true to make ALL disabled links appear as a guest, to test permissions. Alternatively, users with tester rights will also see these links. -->
  <% tester = false %>
  <% if tester || (user_signed_in? && current_user.is_tester?) %>
    <%= render "devise/shared/routes" %>
  <% end %>

  <!-- banned users are blocked for the whole website, may only disconnect -->
  <% if user_signed_in? && current_user.is_banned %>
    <%= render 'layouts/banned' %>
  <% else %>
    <%= yield %>
  <% end %>

</div>
<br>
<footer>
  <div class="well well-sm col-lg-12">
    <ul class="list-unstyled">
      <li class="pull-right">
        (c) 2016
        <%= link_to 'Catstagram', index_path %>
        -
        <a href="http://heig-vd.ch/">HEIG-VD</a>
        -
        Made by
        <a href="https://github.com/paranoodle/">Eléonore d'Agostino</a>
        &
        <a href="https://github.com/ValentinMinder/">Valentin Minder</a>.
      </li>
      <li>
        <a href="#top">Back to top</a>
      </li>
    </ul>
  </div>
</footer>

</body>
</html>

Catstagram/app/views/layouts/index.html.erb
<h1> <%= @title_main %> </h1>

<%= render 'photos/grid' %>

<%= render 'hashtags/grid' %>

<%= render 'cats/grid' %>

<%= render 'users/grid' %>